### PR TITLE
Start of automating web and workers for clickhouse/cloud

### PR DESCRIPTION
**Pull request by fuziontech**

### CODE REVIEW

**Comment by macobo** [comment]
The template used here is out of sync with the one on master + I will be adding more changes in the coming week. Any way to keep the two in sync?

**Comment by fuziontech** [comment]
What do you mean by sync?

**Comment by macobo** [comment]
As in - related improvements in one reach the other one, be it new features, params, docs or something else.

**Comment by fuziontech** [comment]
Ah, I see what you mean. Yeah we can update this to include what you just landed. The properties will be significantly different between the two though since this doesn't bootstrap an entire env, just the ECS side tightly coupled with a postgres instance that is not part of the stack and same with Redis.

Generally these will not be compatible. Especially since event the containers will be based off of different repos like posthog-production vs posthog.

**Comment by fuziontech** [comment]
old news

**Pull request closed without merging**
