### PR TITLE
Add plugins task definition

### PR DESCRIPTION
**Pull request by mariusandra**
I think this should be enough to get the plugin server running in ECS.

I didn't test it, but it should work as this command "just works" elsewhere where we run the `posthog/posthog:latest` container.

Naming wise, even though the package is (for now?) "plugin-server", I just named it "plugins" to be consistent with the "plugins" [task definition](https://github.com/PostHog/posthog/blob/master/task-definition.plugins.json) we use for production.

### CODE REVIEW

**Comment by macobo** [comment]
Should we also kill the old celery container? As-is this is introducing a new container which introduces extra cost for small users.

**Comment by mariusandra** [comment]
We still use celery for [all sorts of other background tasks](https://github.com/PostHog/posthog/blob/734573fbf7d318c421f232204288e6591c5ac034/posthog/celery.py#L40).

**Comment by mariusandra** [comment]
I removed the beat and replaced "-worker-celery" with just "-worker" that calls `bin/docker-worker`, that starts up all three services (beat, celery and plugins). It's the same command that's run in the heroku `worker` dyno for example.

Regarding `beat`, it's the heartbeat that is used for running scheduled tasks. Normally you should have just one per deployment, however we use a locking mechanism that ensures only one beat is running at the time, even if multiple beats are started. Thus I think it's fine to have it merged in. It has been like that in Heroku forever and we haven't had any problems.

**Review by macobo — APPROVED** [review]
Did a quick rebase

**Pull request merged**
